/// THIS FILE IS GENERATED BY r_resources. DO NOT MODIFY MANUALLY.

// ignore_for_file: avoid_classes_with_only_static_members,always_specify_types,lines_longer_than_80_chars,non_constant_identifier_names,prefer_double_quotes,unnecessary_raw_strings,use_raw_strings


class R {
  static const images = _ImageResources();
  static const svg = _SvgResources();
}

class _ImageResources {
  const _ImageResources();

  /// ![](C:\Users\Admin\Documents\Code\FLUTTER\projects\flutter_advanced_boilerplate\assets/images/product/makanan.webp)
  final makanan = r'assets/images/product/makanan.webp';

  /// ![](C:\Users\Admin\Documents\Code\FLUTTER\projects\flutter_advanced_boilerplate\assets/images/product/minuman.jpg)
  final minuman = r'assets/images/product/minuman.jpg';

  /// ![](C:\Users\Admin\Documents\Code\FLUTTER\projects\flutter_advanced_boilerplate\assets/images/product/paket.jpg)
  final paket = r'assets/images/product/paket.jpg';

  /// ![](C:\Users\Admin\Documents\Code\FLUTTER\projects\flutter_advanced_boilerplate\assets/images/product/snack.jpeg)
  final snack = r'assets/images/product/snack.jpeg';

  /// ![](C:\Users\Admin\Documents\Code\FLUTTER\projects\flutter_advanced_boilerplate\assets/images/product/promo1.jpg)
  final promo1 = r'assets/images/product/promo1.jpg';

  /// ![](C:\Users\Admin\Documents\Code\FLUTTER\projects\flutter_advanced_boilerplate\assets/images/product/promo2.png)
  final promo2 = r'assets/images/product/promo2.png';
}

class _SvgResources {
  const _SvgResources();
}
